load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "signtranslator",
    calculators = ["//mediapipe/graphs/sign_translating:sign_translating_gpu_deps"],
)
